### PR TITLE
Fix codestyle a little in Launcher.py

### PR DESCRIPTION
**Pull request by OlegYurchik**
Just trying fix a codestyle a little. If it is a OK, I can refactoring python modules and add linting (pylint or mypy) in CI/CD

### CODE REVIEW

**Comment by jean-baptiste-exorde** [comment]
Hi OlegYurchik, thank you for your interest in the participation module. We are currently doing a full rewrite from scratch of the participation module, with better coding practices (real use of git versioning, tests, stronger CI/CD chain, etc.).

It's not worth putting a lot of effort into trying to improve the current version.

I'll try to merge this PR, hope it doesn't get overwritten.

**Review by MathiasExorde — COMMENTED** [review]
Thanks, good details. Helps reading the code a bit.

**Review by MathiasExorde — APPROVED** [review]

**Comment by OlegYurchik** [comment]
@jean-baptiste-exorde Can I participate to develop new exorde module cli from scratch?

**Comment by MathiasExorde** [comment]
Hi Oleg Yurchik,

We appreciate your will to contribute so much!
Thanks so much already.

As you seen, the code is basic because we are already re developing a new module from scratch. We hired a dedicated engineer, redoing it all with async http io, no threads, with a Web-based UI/UX.

Maybe we can find other things to improve in the short/medium term? There is a lot to do around the module & protocol perhaps.

____

**Comment by OlegYurchik** [comment]
@MathiasExorde Thank you! I have a experience with asyncio and aiohttp, FastAPI, async interaction with different databases. I offer my help in any of your open source projects. I will glad to work with Exorde and do any short/medium term tasks

**Comment by MathiasExorde** [comment]
We have a Community bounty system, to allocate future EXD token to open source tasks. You could be the first one :)

Something very interesting we need is more "scrapers" to be integrated in the architecture: an HTML-based Reddit scraper (no API). A Bitcointalk scraper, etc. Would you like to contribute to this?

**Comment by OlegYurchik** [comment]
@MathiasExorde Sure, it is very interesting for me! Where I can see this tasks?

**Comment by MathiasExorde** [comment]
We can setup something!

**Comment by MathiasExorde** [comment]
@OlegYurchik We will setup a proper page, with more doc/tests, but it might take a while.
So if you want to start contributing now, here is the outline of the task:

**Data collection Task A: Moderate difficulty**
Goal: Scrape the forum "Bitcoin Talk" https://bitcointalk.org/
Requirements: 
- Use Python 3.10
- Must be written as a function, or class (set of functions)
- Input arguments must be: start_datetime (UNIX timestamp)
- Output must be in JSON = all posts titles + comments, posting datetime of all posts is required.
---> for each post/comment, its ID (unique they have topic ID & posts ID I think), datetime & content.
- No API usage, only HTML-based (playwright + aiohttp)


**Data collection Task B: Higher difficulty/importance, higher rewards**
Goal: Scrape Reddit
Requirements: 
- Use Python 3.10
- Must be written as a function, or class (set of functions)
- Input arguments must be: start_datetime (UNIX timestamp), keyword (or keywords)
- -> optional input argument = language (if possible, bonus will be given if you can)
- Output must be in JSON = all posts titles + comments, posting DateTime of all posts is required.
---> for each post/comment, its ID (unique they have topic ID & posts ID I think), DateTime & content.
- No API usage, only HTML-based (playwright + aiohttp)

Note: 
- We only focus on text extraction, nothing else.
- Other sources we want to integrate are, by order of importance: 
  - 9gag.com (titles & comments only)
  - quora.com
  - newsasfacts.com
  - news.ycombinator.com
  - news.google.com
  - trends.gab.com
  - instagram.com  (optional)
  - facebook.com (optional)
  - digg.com
  - in.mashable.com
  - steemit.com
  - hive.blog
 - Reddit is a top priority, Twitter is already ongoing
- We always focus on getting ONLY latest information (last day / since timestamp ideally)

Does that seem OK? :)

Thanks

Mathias Dail
CTO @ Exorde Labs

**Comment by MathiasExorde** [comment]
You can also join Discord, to discuss in open-source-dev-bounties: https://discord.com/channels/754992505241469040/1045041608887914507

**Pull request merged**
